HTTP_TASKS = "/v1/tasks"
HTTP_TASKS_INGEST = "/v1/tasks/ingest"
HTTP_TASKS_LIST = "/v1/tasks"
HTTP_TASK_BY_ID = "/v1/tasks/{task_id}"
HTTP_DECISION_TRACE = "/v1/decision-trace"
HTTP_DATA_DELETION = "/v1/data-deletion-request"
HTTP_CONSENT = "/v1/consent"
HTTP_SELF_REPORT = "/v1/self-report"
HTTP_EXIT_SURVEY = "/v1/exit-survey"
HTTP_ACTIVITY_BUCKETS = "/v1/activity-buckets"
HTTP_PING = "/v1/ping"
HTTP_HEALTH = "/health"

WS_STREAM = "/v1/stream"
